-- Користувачі
CREATE TABLE users
(
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255)        NOT NULL,
    email    VARCHAR(255) UNIQUE NOT NULL,
    role     VARCHAR(20)         NOT NULL
);
-- Додавання тестових даних до користувачів
INSERT INTO users (username, password, email, role)
VALUES ('user', 'user', 'user@test.com', 'USER');


-- Новини та оголошення
CREATE TABLE news
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title      VARCHAR(255) NOT NULL,
    content    TEXT         NOT NULL,
    image_url  TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- Додавання тестових даних до новин
INSERT INTO news (title, content, image_url, created_at)
VALUES ('Стипендії для відмінників',
        'Студенти, які мають середній бал вище 90, можуть подати заявку на підвищену стипендію.',
        'news-1.png',
        NOW()),

       ('Додаткові консультації перед іспитами',
        'Викладачі проведуть додаткові заняття для підготовки до сесії. Перелік консультацій доступний у деканаті.',
        'news-2.png',
        NOW()),

       ('Оновлення бібліотечного фонду',
        'До бібліотеки надійшли нові підручники з програмування та аналізу даних.',
        'news-3.png',
        NOW()),

       ('Реєстрація на весняний семестр',
        'Студенти можуть зареєструватися на курси весняного семестру до 10 березня.',
        'news-4.png',
        NOW());


-- Таблиця предметів
CREATE TABLE subject
(
    id   int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    imageFileName VARCHAR(255) NOT NULL
);

-- Таблиця білетів (наборів питань) для конкретного предмету
CREATE TABLE ticket
(
    id         int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subject_id INT NOT NULL,
    name       VARCHAR(255),
    FOREIGN KEY (subject_id) REFERENCES subject (id)
);

-- Таблиця питань білета
CREATE TABLE question
(
    id             int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ticket_id      INT  NOT NULL,
    question_text  TEXT NOT NULL,
    question_order INT,
    FOREIGN KEY (ticket_id) REFERENCES ticket (id)
);

-- Таблиця варіантів відповідей для питання
CREATE TABLE answer_option
(
    id          int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question_id INT          NOT NULL,
    option_text VARCHAR(255) NOT NULL,
    is_correct  BOOLEAN DEFAULT false,
    FOREIGN KEY (question_id) REFERENCES question (id)
);

-- 1. Заповнення таблиці subject
INSERT INTO subject (name, imagefilename)
VALUES ('Дискретна математика', 'discrete.png' );
INSERT INTO subject (name, imagefilename)
VALUES ('Математичний аналіз', 'matan.png');
INSERT INTO subject (name, imagefilename)
VALUES ('ЛААГ', 'lingeo.png');
INSERT INTO subject (name, imagefilename)
VALUES ('Програмування на С#', 'csh.png');
INSERT INTO subject (name, imagefilename)
VALUES ('Програмування на С++', 'cpp.png');
INSERT INTO subject (name, imagefilename)
VALUES ('Основи баз даних', 'dbase.png');
INSERT INTO subject (name, imagefilename)
VALUES ('Програмування на Python', 'progpyth.png');
INSERT INTO subject (name, imagefilename)
VALUES ('Філософія', 'fylo.png');


----------------------------------------------------------------
-- Вставка білетів, питань та варіантів відповідей
-- ***Subject 1: Дискретна математика***
-- Ticket Inserts
INSERT INTO ticket (subject_id, name) VALUES (1, 'Дискретна математика - Тест 1');
INSERT INTO ticket (subject_id, name) VALUES (1, 'Дискретна математика - Тест 2');

-- Test 1 (Ticket id = 1)
-- Question 1
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (1, 'Яке з наступних тверджень описує принцип математичної індукції?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (1, 'Якщо твердження справджується для n, і з встановленого базового випадку випливає справдження для n+1, то воно справджується для всіх натуральних чисел.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (1, 'Доведення починається з припущення справедливості твердження для всіх чисел без базового випадку.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (1, 'Індивідуальне доведення для кожного конкретного n є частиною індукції.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (1, 'Твердження для n+1 не залежить від справедливості для n.', false);

-- Question 2
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (1, 'Що таке комбінація в контексті вибірок без врахування порядку?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (2, 'Кількість способів обрати k елементів з n без врахування послідовності, що обчислюється за формулою C(n,k) = n!/(k!(n-k)!).', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (2, 'Кількість способів розташувати k елементів у певному порядку.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (2, 'Метод розбиття множини на підмножини.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (2, 'Процес вибору елементів з повторенням.', false);

-- Question 3
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (1, 'Яке з наступних визначень є правильним для графа?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (3, 'Граф – це множина вершин, з’єднаних ребрами, де ребра можуть бути орієнтованими або неорієнтованими.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (3, 'Граф – це лише набір точок без з’єднувальних ліній.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (3, 'Граф – це множина ліній, що не мають кінцевих точок.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (3, 'Граф – це таблиця зв’язків між числами.', false);

-- Question 4
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (1, 'Що таке булева алгебра?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (4, 'Булева алгебра вивчає логічні операції з двома значеннями – істинно і хибно, і є основою для цифрових схем.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (4, 'Булева алгебра є алгеброю дійсних чисел.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (4, 'Булева алгебра розглядає лише операції додавання і множення.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (4, 'Булева алгебра використовується для розрахунку інтегралів.', false);

-- Question 5
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (1, 'Що таке теорія множин?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (5, 'Теорія множин – це галузь математики, що вивчає властивості та операції над множинами об’єктів.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (5, 'Теорія множин обчислює значення функцій через інтегрування.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (5, 'Теорія множин аналізує числові ряди шляхом підсумовування елементів.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (5, 'Теорія множин стосується тільки порівняння двох чисел.', false);

-- Test 2 (Ticket id = 2)
-- Question 6
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (2, 'Як застосовується принцип індукції для доведення нерівностей?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (6, 'Спочатку встановлюється базовий випадок, потім показується, що якщо нерівність справедлива для n, вона справедлива і для n+1.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (6, 'Нерівність доводиться, перевіряючи її лише для кількох випадкових значень n.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (6, 'Використовуються лише числові підстановки без логічного переходу.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (6, 'Метод індукції не підходить для доведення нерівностей.', false);

-- Question 7
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (2, 'Що таке перестановки і як їх обчислюють?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (7, 'Перестановки – це розташування елементів у певному порядку, їх кількість обчислюється як n! для n елементів.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (7, 'Перестановки – це вибір елементів без врахування порядку, що обчислюється за формулою C(n,k).', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (7, 'Перестановки не мають формального обчислення в комбінаториці.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (7, 'Перестановки визначаються через суму елементів множини.', false);

-- Question 8
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (2, 'Яке твердження описує поняття зв’язності графа?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (8, 'Граф є зв’язним, якщо існує шлях між будь-якою парою його вершин.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (8, 'Граф є зв’язним, якщо він має хоча б один цикл.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (8, 'Граф зв’язаний, коли кількість вершин перевищує кількість ребер.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (8, 'Зв’язність графа залежить від кількості компонентів, що завжди дорівнюють нулю.', false);

-- Question 9
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (2, 'Що таке рекурентність і як її розв’язують?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (9, 'Рекурентність – це рівняння, яке задає послідовність через попередні значення; розв’язують її або підстановкою, або знаходженням явної формули.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (9, 'Рекурентність визначає статистичні залежності і розв’язується методом інтегрування.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (9, 'Рекурентність – це метод доказу, що не використовується для отримання явної формули.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (9, 'Рекурентність використовується лише для обчислення сум рядів.', false);

-- Question 10
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (2, 'Яким способом можна оцінити розмір максимального незалежного множини в графі?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (10, 'Максимальне незалежне множину шукають за допомогою алгоритмів оптимізації, що перебирають підмножини вершин, забезпечуючи відсутність суміжних пар.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (10, 'Розмір незалежної множини обчислюють шляхом знаходження найкоротшого шляху в графі.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (10, 'Максимальну незалежну множину знаходять простим підсумовуванням степенів вершин.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (10, 'Цей розмір визначається числом вершин мінус кількість ребер.', false);

----------------------------------------------------------------
-- ***Subject 2: Математичний аналіз***
-- Ticket Inserts
INSERT INTO ticket (subject_id, name) VALUES (2, 'Математичний аналіз - Тест 1');
INSERT INTO ticket (subject_id, name) VALUES (2, 'Математичний аналіз - Тест 2');

-- Test 1 (Ticket id = 3)
-- Question 11
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (3, 'Що таке границя функції f(x) при наближенні x до певного значення?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (11, 'Границя – це значення, до якого прямує f(x), коли x наближається до заданої точки або нескінченності.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (11, 'Границя – це точне значення f(x) при x рівному цій точці.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (11, 'Границя – це середнє арифметичне значень функції.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (11, 'Границя не є математично визначеною поняттям.', false);

-- Question 12
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (3, 'Як визначається неперервність функції в точці?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (12, 'Функція неперервна в точці, якщо границя f(x) при x, що прямує до цієї точки, дорівнює f(точка).', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (12, 'Функція неперервна, якщо її похідна існує в цій точці.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (12, 'Функція неперервна, якщо її значення завжди додатні.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (12, 'Функція неперервна, якщо вона визначена на всіх числах.', false);

-- Question 13
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (3, 'Що таке похідна функції і як її можна інтерпретувати геометрично?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (13, 'Похідна – це границя відношення приросту функції до приросту аргументу; геометрично інтерпретується як нахил дотичної до графіка функції.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (13, 'Похідна – це значення функції в даній точці.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (13, 'Похідна – це площа під графіком функції.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (13, 'Похідна – це інтеграл функції.', false);

-- Question 14
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (3, 'Яке з тверджень описує правило Лопіталя?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (14, 'Правило Лопіталя дозволяє обчислити границю співвідношення двох функцій, якщо обидві набувають невизначеного вигляду 0/0 або ∞/∞.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (14, 'Правило Лопіталя використовується для обчислення похідних.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (14, 'Правило Лопіталя дає точне значення інтегралу від функції.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (14, 'Правило Лопіталя застосовується для розв’язання диференціальних рівнянь.', false);

-- Question 15
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (3, 'Що таке визначений інтеграл і яка його геометрична інтерпретація?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (15, 'Визначений інтеграл – це границя суми значень функції на розбитому інтервалі, що геометрично означає площу області під графіком функції.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (15, 'Визначений інтеграл – це просто сума значень функції у вибраних точках.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (15, 'Визначений інтеграл показує похідну функції.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (15, 'Визначений інтеграл використовується для обчислення середнього значення функції.', false);

-- Test 2 (Ticket id = 4)
-- Question 16
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (4, 'Що таке розкладання Тейлора і для чого воно використовується?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (16, 'Розкладання Тейлора дозволяє апроксимувати функцію поліноміальною сумою на околі певної точки.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (16, 'Розкладання Тейлора використовується для знаходження коренів рівнянь.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (16, 'Розкладання Тейлора дає точне значення інтегралу функції.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (16, 'Розкладання Тейлора є методом чисельного інтегрування.', false);

-- Question 17
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (4, 'Як за допомогою похідних знаходять екстремуми функції?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (17, 'Шукають критичні точки, де похідна дорівнює 0 або не існує, а потім досліджують знак другої похідної.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (17, 'Екстремуми визначаються як значення функції в точках розриву.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (17, 'Функція має екстремум, коли її перша похідна збігається до нескінченності.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (17, 'Похідні не використовують для пошуку екстремумів.', false);

-- Question 18
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (4, 'Що таке асимптота графіка функції?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (18, 'Асимптота – це пряма, до якої графік функції прямує, коли x або f(x) наближаються до нескінченності.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (18, 'Асимптота – це точка перетину графіка з віссю.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (18, 'Асимптота показує екстремум функції.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (18, 'Асимптота визначається як значення функції в точці розриву.', false);

-- Question 19
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (4, 'Як правило Коші допомагає дослідити збіжність послідовностей?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (19, 'За допомогою співвідношення різниць членів послідовності можна визначити її збіжність, використовуючи критерій, подібний до індукції.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (19, 'Правило Коші застосовують для диференціального рівняння, а не для послідовностей.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (19, 'Правило Коші визначає асимптотичну поведінку функції, а не послідовності.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (19, 'Правило Коші – це критерій розриву функції.', false);

-- Question 20
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (4, 'Що таке збіжність числових рядів?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (20, 'Збіжність ряду означає, що сума його нескінченно багатьох членів прямує до скінченної межі.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (20, 'Збіжність ряду визначається як відсутність будь-якого змінного члена.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (20, 'Чим більше членів ряду, тим менша збіжність.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (20, 'Збіжність ряду залежить від його перетворення Фур’є.', false);

----------------------------------------------------------------
-- ***Subject 3: Лінійна алгебра і аналітична геометрія***
-- Вставка білетів для предмету (subject_id = 3)
INSERT INTO ticket (subject_id, name)
VALUES (3, 'Лінійна алгебра і аналітична геометрія - Тест 1');
INSERT INTO ticket (subject_id, name)
VALUES (3, 'Лінійна алгебра і аналітична геометрія - Тест 2');

----------------------------------------------------------------
-- Тест 1 (припускаємо, що id білета = 5)
-- Питання 1
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (5, 'Що таке вектор і як його представляють у лінійній алгебрі?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (21, 'Вектор – це елемент векторного простору, що характеризується напрямком і величиною, і зазвичай представляється стрілкою.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (21, 'Вектор – це просто число, що описує довжину.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (21, 'Вектор – це множина точок на площині.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (21, 'Вектор – це функція, що приймає значення з простору.', false);

-- Питання 2
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (5, 'Що таке матриця і для чого вона використовується?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (22, 'Матриця – це прямокутна таблиця чисел, яка використовується для представлення та обчислення лінійних перетворень.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (22, 'Матриця – це послідовність елементів, що характеризує ненульову константу.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (22, 'Матриця – це набір випадкових даних без структури.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (22, 'Матриця – це просто обчислювальний алгоритм для інтегрування.', false);

-- Питання 3
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (5, 'Що таке визначник матриці і яка його геометрична інтерпретація?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (23, 'Визначник – це скалярне число, що характеризує масштабне перетворення, наприклад, зміну площі або об’єму при лінійних перетвореннях.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (23, 'Визначник – це вектор, що вказує напрямок коливань.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (23, 'Визначник – це функція, що перетворює матрицю на рядок.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (23, 'Визначник – це перетворення, яке не має геометричного значення.', false);

-- Питання 4
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (5, 'Що таке обернена матриця і коли вона існує?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (24, 'Обернена матриця – це матриця, що при множенні на початкову дає одиничну матрицю; існує лише для квадратних матриць з визначником, відмінним від нуля.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (24, 'Обернена матриця завжди існує для будь-якої прямокутної матриці.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (24, 'Обернена матриця – це просто транскрипція матриці без зміни її елементів.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (24, 'Обернена матриця використовується для знаходження власних чисел.', false);

-- Питання 5
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (5, 'Яке з наступних тверджень правильно характеризує лінійну залежність векторів?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (25, 'Вектори є лінійно залежними, якщо один із них можна виразити як лінійну комбінацію інших.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (25, 'Вектори є лінійно залежними, якщо вони мають однакову довжину.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (25, 'Вектори є лінійно залежними, якщо їхній добуток дорівнює нулю.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (25, 'Вектори є лінійно залежними, якщо вони орієнтовані у протилежні напрямки.', false);

----------------------------------------------------------------
-- Тест 2 (припускаємо, що id білета = 6)
-- Питання 6
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (6, 'Що таке система лінійних рівнянь?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (26, 'Система лінійних рівнянь – це набір лінійних рівнянь, що описують перетин гіперплощин.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (26, 'Система лінійних рівнянь містить рівняння з нелінійними виразами.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (26, 'Система лінійних рівнянь – це одне рівняння з багатьма невідомими без спільного розв’язку.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (26, 'Система лінійних рівнянь описує траєкторію руху об’єкта в просторі.', false);

-- Питання 7
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (6, 'Як застосовується метод Гаусса для розв’язання системи лінійних рівнянь?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (27, 'Метод Гаусса використовує елементарні перетворення для приведення матриці коефіцієнтів до верхньотрикутного вигляду з метою спрощення розв’язання системи.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (27, 'Метод Гаусса полягає у знаходженні визначника матриці коефіцієнтів.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (27, 'Метод Гаусса застосовується для множення матриць.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (27, 'Метод Гаусса використовується для розрахунку інтегралів від матричних функцій.', false);

-- Питання 8
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (6, 'Що таке власні значення та власні вектори матриці?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (28, 'Власні значення – це скалярні показники, а власні вектори – ненульові вектори, що задовольняють рівняння A*v = λ*v для квадратної матриці A.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (28, 'Власні значення і власні вектори використовуються для знаходження обернених матриць.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (28, 'Власні значення – це координати вектора, а власні вектори – це значення функції.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (28, 'Власні значення і вектори визначаються методом Гаусса.', false);

-- Питання 9
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (6, 'Яку геометричну інтерпретацію має визначник матриці?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (29, 'Визначник матриці характеризує масштаб, на який лінійне перетворення змінює площу (у 2D) або об’єм (у 3D).', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (29, 'Визначник матриці вказує на напрямок руху точок у просторі.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (29, 'Визначник матриці визначає тип кривої, яку описує система рівнянь.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (29, 'Визначник матриці використовується для обчислення власних значень.', false);

-- Питання 10
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (6, 'Що таке скалярний добуток векторів і яка його геометрична інтерпретація?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (30, 'Скалярний добуток – це операція, що обчислюється як добуток модулів векторів на косинус кута між ними; він дає інформацію про їхню паралельність.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (30, 'Скалярний добуток – це операція, що визначає векторний добуток векторів.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (30, 'Скалярний добуток використовується для обчислення площі паралелепіпеда, утвореного векторами.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (30, 'Скалярний добуток застосовується для знаходження власних значень матриці.', false);

----------------------------------------------------------------
-- ***Subject 4: Програмування на С#***
-- Ticket Inserts
INSERT INTO ticket (subject_id, name) VALUES (4, 'Програмування на С# - Тест 1');
INSERT INTO ticket (subject_id, name) VALUES (4, 'Програмування на С# - Тест 2');

-- Test 1 (Ticket id = 7)
-- Question 31
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (7, 'Що таке CLR і яку роль він відіграє в .NET?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (31, 'CLR (Common Language Runtime) є середовищем виконання для управління виконанням коду на .NET, забезпечуючи керування пам’яттю, безпеку та інші сервіси.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (31, 'CLR є інтерфейсом користувача для розробки додатків.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (31, 'CLR – це база даних для зберігання коду.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (31, 'CLR відповідає за компіляцію коду C# безпосередньо в машинний код.', false);

-- Question 32
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (7, 'Що таке managed code в C#?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (32, 'Managed code виконується під керуванням середовища CLR, що забезпечує автоматичне управління пам’яттю та безпеку.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (32, 'Managed code – це код, який виконується поза керуванням CLR.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (32, 'Managed code означає код, який не компілюється.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (32, 'Managed code вказує на код, що написаний мовою C++.', false);

-- Question 33
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (7, 'Як працює garbage collection в C#?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (33, 'Garbage collection автоматично звільняє пам’ять, яку більше не використовують, зменшуючи ризик витоків пам’яті.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (33, 'Garbage collection вимагає ручного виклику користувачем після кожної операції.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (33, 'Garbage collection відповідає за компіляцію коду.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (33, 'Garbage collection використовується для оптимізації роботи баз даних.', false);

-- Question 34
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (7, 'Що таке делегати і для чого вони використовуються?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (34, 'Делегати – це тип даних, що зберігає посилання на методи, дозволяючи викликати їх через змінну.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (34, 'Делегати є класами, що реалізують інтерфейси.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (34, 'Делегати використовуються для роботи з базами даних.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (34, 'Делегати – це методи з автоматичним очищенням пам’яті.', false);

-- Question 35
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (7, 'Яка основна відмінність між класами і структурами в C#?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (35, 'Класи є типами посилань, тоді як структури – типами значення.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (35, 'Класи можна використовувати лише для графічних інтерфейсів, а структури – для обчислень.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (35, 'Структури підтримують наслідування, а класи – ні.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (35, 'Немає жодної різниці між класами і структурами.', false);

-- Test 2 (Ticket id = 8)
-- Question 36
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (8, 'Що таке LINQ і яка його основна перевага?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (36, 'LINQ дозволяє писати запити до колекцій даних у синтаксисі, інтегрованому в C#, що робить код більш читабельним.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (36, 'LINQ використовується для роботи з графічними об’єктами.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (36, 'LINQ є мовою програмування, незалежною від C#.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (36, 'LINQ автоматично оптимізує SQL-запити в базі даних.', false);

-- Question 37
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (8, 'Що таке події в C#?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (37, 'Події дозволяють об’єктам повідомляти про зміни, забезпечуючи реалізацію моделі “спостерігач”.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (37, 'Події – це методи, що викликаються автоматично при старті програми.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (37, 'Події використовуються для управління пам’яттю.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (37, 'Події – це винятки, які генеруються під час помилок.', false);

-- Question 38
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (8, 'Що таке інтерфейси і яку роль вони відіграють?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (38, 'Інтерфейси задають контракт, який реалізують класи, що забезпечує узагальнення і модульність коду.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (38, 'Інтерфейси є конкретними реалізаціями методів.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (38, 'Інтерфейси використовуються тільки для роботи з базами даних.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (38, 'Інтерфейси дозволяють об’єктам зберігати стан.', false);

-- Question 39
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (8, 'Як працює асинхронність в C#?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (39, 'Асинхронність дозволяє виконувати операції у фоновому режимі без блокування головного потоку виконання.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (39, 'Асинхронність є еквівалентом багатопоточності без використання потоків.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (39, 'Асинхронність гарантує, що операції виконуються синхронно.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (39, 'Асинхронність використовується тільки для роботи з файлами.', false);

-- Question 40
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (8, 'Що таке обробка винятків (exception handling) в C#?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (40, 'Обробка винятків дозволяє перехоплювати і коректно обробляти помилки під час виконання програми.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (40, 'Обробка винятків автоматично зупиняє виконання програми без повідомлення.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (40, 'Обробка винятків відсутня в C# і замінюється перевіркою типів даних.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (40, 'Обробка винятків служить для оптимізації швидкодії компілятора.', false);

----------------------------------------------------------------
-- ***Subject 5: Програмування на С++***
-- Ticket Inserts
INSERT INTO ticket (subject_id, name) VALUES (5, 'Програмування на С++ - Тест 1');
INSERT INTO ticket (subject_id, name) VALUES (5, 'Програмування на С++ - Тест 2');

-- Test 1 (Ticket id = 9)
-- Question 41
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (9, 'Що таке вказівники в С++ і як правильно ними користуватися?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (41, 'Вказівники є змінними, що зберігають адреси інших змінних, що дозволяє працювати з динамічною пам’яттю.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (41, 'Вказівники – це константи, які не можна змінити.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (41, 'Вказівники використовуються тільки для арифметичних операцій.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (41, 'Вказівники – це спеціальний тип, який не має адресної семантики.', false);

-- Question 42
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (9, 'Що таке об’єктно-орієнтоване програмування в С++?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (42, 'ООП – це парадигма, яка використовує класи та об’єкти для моделювання даних і поведінки.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (42, 'ООП виключно забезпечує функціональний підхід до програмування.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (42, 'ООП – це метод оптимізації швидкодії програм.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (42, 'ООП – це засіб роботи з базами даних в С++.', false);

-- Question 43
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (9, 'Як працює передача параметрів за посиланням у С++?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (43, 'Передача за посиланням дозволяє функції отримувати доступ до оригінального аргументу, без створення копії.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (43, 'При передачі за посиланням завжди створюється копія аргументу.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (43, 'Передача за посиланням застосовується тільки для змінних типу int.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (43, 'Передача за посиланням значно уповільнює роботу програми.', false);

-- Question 44
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (9, 'Які основні принципи механізму RAII в С++?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (44, 'RAII гарантує, що ресурси будуть звільнені автоматично при виході з області дії об’єкта.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (44, 'RAII означає ручне звільнення пам’яті без використання деструкторів.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (44, 'RAII використовується для оптимізації циклів в С++.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (44, 'RAII забезпечує виключно нульовий вплив на швидкодію.', false);

-- Question 45
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (9, 'Що таке шаблони (templates) в С++?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (45, 'Шаблони дозволяють писати універсальний код, що працює з будь-якими типами даних, забезпечуючи узагальнене програмування.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (45, 'Шаблони є засобом для роботи з вказівниками.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (45, 'Шаблони використовується лише для оптимізації функцій.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (45, 'Шаблони дозволяють автоматично створювати класи без визначення методів.', false);

-- Test 2 (Ticket id = 10)
-- Question 46
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (10, 'Як працює спадкування в С++?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (46, 'Спадкування дозволяє одному класу успадкувати властивості і методи іншого, сприяючи повторному використанню коду.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (46, 'Спадкування означає копіювання даних з одного класу в інший без відношення.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (46, 'Спадкування використовується тільки для створення шаблонів.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (46, 'Спадкування не підтримується в сучасному С++.', false);

-- Question 47
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (10, 'Що таке поліморфізм і як його реалізують в С++?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (47, 'Поліморфізм дозволяє об’єктам різних класів використовувати спільний інтерфейс, реалізований через віртуальні функції.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (47, 'Поліморфізм означає примусовий виклик функцій базового класу.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (47, 'Поліморфізм не реалізується в С++ через відсутність інтерфейсів.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (47, 'Поліморфізм використовується лише для обробки помилок.', false);

-- Question 48
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (10, 'Що таке оператори new і delete в С++?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (48, 'Оператори new і delete використовуються для динамічного виділення та звільнення пам’яті.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (48, 'Оператори new і delete автоматично перезавантажують процесор.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (48, 'Оператори new і delete використовуються для ініціалізації класів.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (48, 'Оператори new і delete забезпечують безпечний доступ до файлів.', false);

-- Question 49
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (10, 'Як використовують стандартну бібліотеку шаблонів (STL) в С++?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (49, 'STL надає готові шаблонні класи та алгоритми (як-от вектори, списки, алгоритми сортування), що полегшують розробку.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (49, 'STL є засобом компіляції коду для оптимізації процесора.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (49, 'STL використовується виключно для роботи з базами даних.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (49, 'STL – це набір функцій для математичних обчислень.', false);

-- Question 50
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (10, 'Які відмінності між класичним та сучасним С++?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (50, 'Сучасний С++ підтримує нові стандарти, такі як auto, лямбда-функції, розширену STL, смарт-вказівники і безпечну обробку пам’яті.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (50, 'Класичний С++ використовує тільки процедуральний підхід без підтримки ООП.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (50, 'Сучасний С++ не підтримує шаблони, на відміну від класичного С++.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (50, 'Немає значних відмінностей між класичним і сучасним С++.', false);

----------------------------------------------------------------
-- ***Subject 6: Основи баз даних***
-- Ticket Inserts
INSERT INTO ticket (subject_id, name) VALUES (6, 'Основи баз даних - Тест 1');
INSERT INTO ticket (subject_id, name) VALUES (6, 'Основи баз даних - Тест 2');

-- Test 1 (Ticket id = 11)
-- Question 51
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (11, 'Що таке реляційна база даних?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (51, 'Реляційна база даних організована у вигляді таблиць, де дані пов’язані через ключі.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (51, 'Реляційна база даних зберігає дані у вигляді ієрархічного дерева.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (51, 'Реляційна база даних не допускає використання SQL.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (51, 'Реляційна база даних організована як набір неструктурованих документів.', false);

-- Question 52
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (11, 'Що таке первинний ключ і навіщо він потрібен?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (52, 'Первинний ключ унікально ідентифікує кожен запис у таблиці, забезпечуючи унікальність даних.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (52, 'Первинний ключ може повторюватися у таблиці.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (52, 'Первинний ключ визначає тип даних в таблиці.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (52, 'Первинний ключ використовується для з’єднання таблиць, але може бути нульовим.', false);

-- Question 53
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (11, 'Що таке нормалізація даних?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (53, 'Нормалізація – це процес структурування даних для зменшення надлишковості і запобігання аномаліям при оновленні.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (53, 'Нормалізація – це метод шифрування даних.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (53, 'Нормалізація означає створення індексів для швидкого пошуку.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (53, 'Нормалізація – це об’єднання кількох таблиць в одну.', false);

-- Question 54
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (11, 'Що таке SQL-запит?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (54, 'SQL-запит – це інструкція, яка дозволяє працювати з даними в реляційних базах даних за допомогою мови SQL.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (54, 'SQL-запит – це програма, що створює таблиці.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (54, 'SQL-запит використовується для зберігання даних в кеш.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (54, 'SQL-запит – це метод шифрування інформації.', false);

-- Question 55
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (11, 'Яка різниця між INNER JOIN і LEFT JOIN?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (55, 'INNER JOIN повертає тільки ті записи, що є у обох таблицях, а LEFT JOIN повертає всі записи з лівої таблиці і співпадаючі з правою.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (55, 'LEFT JOIN повертає тільки записи з правої таблиці.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (55, 'INNER JOIN і LEFT JOIN виконують однакову операцію.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (55, 'LEFT JOIN повертає всі записи, а INNER JOIN – лише перший запис.', false);

----------------------------------------------------------------
-- Test 2 (Ticket id = 12)
-- Question 56
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (12, 'Що таке транзакція в базах даних?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (56, 'Транзакція – це послідовність операцій, що виконується як єдина логічна одиниця з властивостями ACID.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (56, 'Транзакція – це запит для отримання даних.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (56, 'Транзакція використовується тільки для резервного копіювання.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (56, 'Транзакція – це метод з’єднання таблиць.', false);

-- Question 57
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (12, 'Що таке індексування в базах даних?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (57, 'Індексація покращує швидкодію пошуку даних, створюючи додаткову структуру, що вказує на місце розташування записів.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (57, 'Індексація означає об’єднання декількох таблиць.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (57, 'Індексація відповідає за нормалізацію даних.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (57, 'Індексація використовується для шифрування записів.', false);

-- Question 58
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (12, 'Що таке ACID властивості транзакцій?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (58, 'ACID – це набір властивостей (атомарність, консистентність, ізольованість, довговічність), необхідних для коректного виконання транзакцій.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (58, 'ACID означає автоматичне контроль даних.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (58, 'ACID використовується для індексації бази даних.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (58, 'ACID – це алгоритм оптимізації запитів.', false);

-- Question 59
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (12, 'Як працює система управління базами даних (СУБД)?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (59, 'СУБД забезпечує створення, збереження, обробку і захист даних, реалізуючи мову SQL та інші інтерфейси.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (59, 'СУБД – це сукупність операцій для обчислення матриць.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (59, 'СУБД автоматично генерує програмний код для додатків.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (59, 'СУБД використовується лише для аналітики бізнес-процесів.', false);

-- Question 60
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (12, 'Що таке NoSQL бази даних?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (60, 'NoSQL – це категорія баз даних, що не використовує реляційну модель і часто призначена для роботи з великими обсягами неструктурованих даних.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (60, 'NoSQL – це база даних, що застосовується лише для резервного копіювання.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (60, 'NoSQL бази даних використовують SQL як основну мову запитів.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (60, 'NoSQL – це технологія для створення графічних інтерфейсів баз даних.', false);

----------------------------------------------------------------
-- ***Subject 7: Програмування на Python***
-- Ticket Inserts
INSERT INTO ticket (subject_id, name) VALUES (7, 'Програмування на Python - Тест 1');
INSERT INTO ticket (subject_id, name) VALUES (7, 'Програмування на Python - Тест 2');

-- Test 1 (Ticket id = 13)
-- Question 61
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (13, 'Які основні особливості мови Python?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (61, 'Python є інтерпретованою мовою з динамічною типізацією і зручною синтаксисом для розробки різноманітних додатків.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (61, 'Python є компільованою мовою з статичною типізацією.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (61, 'Python використовується лише для веб-розробки.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (61, 'Python не підтримує об’єктно-орієнтоване програмування.', false);

-- Question 62
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (13, 'Яка різниця між списком та кортежем у Python?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (62, 'Списки є змінними (mutable), а кортежі – незмінними (immutable).', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (62, 'Кортежі є змінними, а списки – незмінними.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (62, 'Обидва типи є незмінними.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (62, 'Обидва типи є змінними, різниця лише синтаксична.', false);

-- Question 63
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (13, 'Яку роль відіграє конструкція with в Python?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (63, 'Конструкція with забезпечує безпечне відкриття й автоматичне закриття ресурсів, таких як файли.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (63, 'Конструкція with використовується для створення лямбда-функцій.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (63, 'Конструкція with є засобом виняткової обробки помилок.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (63, 'Конструкція with використовується для імпорту модулів.', false);

-- Question 64
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (13, 'Що таке декоратори у Python?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (64, 'Декоратори – це функції, що приймають іншу функцію і розширюють або змінюють її поведінку без модифікації її коду.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (64, 'Декоратори – це методи класів для ініціалізації об’єктів.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (64, 'Декоратори використовуються для управління пам’яттю в Python.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (64, 'Декоратори – це спеціальний тип змінних.', false);

-- Question 65
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (13, 'Що таке генератори в Python?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (65, 'Генератори – це функції, що повертають послідовність значень за допомогою оператора yield, дозволяючи ефективно працювати з великими даними.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (65, 'Генератори є типом списків, що завжди обчислюються одразу.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (65, 'Генератори використовуються для зберігання інформації в базі даних.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (65, 'Генератори – це окремий тип класів в Python.', false);

-- Test 2 (Ticket id = 14)
-- Question 66
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (14, 'Як працює система обробки винятків у Python?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (66, 'За допомогою блоків try, except, finally для перехоплення та обробки помилок під час виконання коду.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (66, 'За допомогою механізму імпорту модулів винятки не обробляються.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (66, 'Python не підтримує обробку помилок через синтаксичну структуру.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (66, 'Обробка винятків відбувається автоматично без можливості перехоплення.', false);

-- Question 67
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (14, 'Що таке модулі та пакети в Python?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (67, 'Модулі – це окремі файли з кодом, а пакети – каталоги, що містять модулі, організовувані у єдину структуру.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (67, 'Модулі та пакети – це синоніми і використовуються взаємозамінно.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (67, 'Пакети створюються автоматично при встановленні Python.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (67, 'Модулі використовуються для обчислення математичних операцій, а пакети – для роботи з файлами.', false);

-- Question 68
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (14, 'Як здійснюється читання та запис файлів у Python?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (68, 'Файли читаються і записуються за допомогою функцій open, read, write і використання менеджерів контексту для автоматичного закриття.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (68, 'Читання та запис файлів здійснюється автоматично без використання будь-яких функцій.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (68, 'Файли можна читати лише у форматі JSON.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (68, 'Запис файлів вимагає використання операторів імпорту.', false);

-- Question 69
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (14, 'Що таке lambda-функції в Python?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (69, 'Lambda-функції – це анонімні функції, що визначаються в одному виразі і часто використовуються як короткі функції для однократного застосування.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (69, 'Lambda-функції є обов’язковим класовим методом.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (69, 'Lambda-функції використовуються для управління потоками.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (69, 'Lambda-функції – це модулі для роботи з базами даних.', false);

-- Question 70
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (14, 'Як використовувати бібліотеку Pandas для аналізу даних?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (70, 'Pandas надає структури даних (DataFrame, Series) і функції для швидкого та ефективного аналізу та обробки великих обсягів даних.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (70, 'Pandas використовується виключно для графічного відображення даних.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (70, 'Pandas є стандартною бібліотекою для роботи з веб-серверами.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (70, 'Pandas не підтримує роботу з числовими даними.', false);

----------------------------------------------------------------
-- ***Subject 8: Філософія***
-- Ticket Inserts
INSERT INTO ticket (subject_id, name) VALUES (8, 'Філософія - Тест 1');
INSERT INTO ticket (subject_id, name) VALUES (8, 'Філософія - Тест 2');

-- Test 1 (Ticket id = 15)
-- Question 71
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (15, 'Що таке онтологія в філософії?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (71, 'Онтологія вивчає природу буття та існування.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (71, 'Онтологія займається вивченням моральних норм.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (71, 'Онтологія розглядає стратегії мислення.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (71, 'Онтологія – це метод наукового експерименту.', false);

-- Question 72
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (15, 'Що таке епістемологія і які її основні питання?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (72, 'Епістемологія досліджує природу пізнання, джерела знань та критерії істинності.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (72, 'Епістемологія вивчає емоції людини.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (72, 'Епістемологія займається аналізом логічних парадоксів.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (72, 'Епістемологія визначає соціальні структури суспільства.', false);

-- Question 73
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (15, 'Які основні філософські течії існують?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (73, 'Серед основних течій – раціоналізм, емпіризм, екзистенціалізм, феноменологія, та інші.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (73, 'Філософія існує лише як єдина універсальна течія.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (73, 'Філософські течії класифікують тільки на позитивні та негативні.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (73, 'Основних філософських течій немає, а всі думки є випадковими.', false);

-- Question 74
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (15, 'Що таке раціоналізм?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (74, 'Раціоналізм стверджує, що основою знань є розум та логічне мислення.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (74, 'Раціоналізм базується на емпіричних спостереженнях.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (74, 'Раціоналізм вважає, що знання надходять виключно через інтуїцію.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (74, 'Раціоналізм – це філософський напрямок, що не визнає логіку.', false);

-- Question 75
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (15, 'Що таке емпіризм?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (75, 'Емпіризм стверджує, що знання базуються на досвіді, спостереженнях і експериментах.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (75, 'Емпіризм відкидає досвід як джерело знань.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (75, 'Емпіризм розглядає мову як основний інструмент пізнання.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (75, 'Емпіризм є методом математичного аналізу.', false);

-- Test 2 (Ticket id = 16)
-- Question 76
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (16, 'Що таке екзистенціалізм і хто його представники?', 1);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (76, 'Екзистенціалізм – це філософський напрямок, що підкреслює індивідуальну свободу і відповідальність; його представниками є Жан-Поль Сартр, Альбер Камю тощо.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (76, 'Екзистенціалізм пов’язують виключно з класичною античною філософією.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (76, 'Екзистенціалізм є течією в математиці.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (76, 'Екзистенціалізм не має представників у сучасній філософії.', false);

-- Question 77
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (16, 'Як філософи розуміють поняття "добро"?', 2);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (77, 'Поняття "добро" має різні трактування – від етичного і морального до утилітарного; воно досліджується в етиці та метафізиці.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (77, 'Добро визначається виключно як максимізація економічної вигоди.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (77, 'Добро є об’єктивним показником кількісних характеристик.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (77, 'Добро визначається лише через біологічні процеси.', false);

-- Question 78
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (16, 'Що таке метафізика в традиції західної філософії?', 3);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (78, 'Метафізика займається вивченням основних принципів буття, реальності і природи існування, що виходить за межі фізичного світу.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (78, 'Метафізика – це сукупність математичних законів природи.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (78, 'Метафізика обмежується логічним аналізом мови.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (78, 'Метафізика є наукою про зірки і планети.', false);

-- Question 79
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (16, 'Як виникло поняття "етика" у філософській традиції?', 4);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (79, 'Етика виникла як розділ філософії, що досліджує природу добра і зла, моральні норми та поведінку людини.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (79, 'Етика була винайдена виключно в науці про політику.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (79, 'Етика є методом розрахунку економічних показників.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (79, 'Етика – це наука про мову та комунікації.', false);

-- Question 80
INSERT INTO question (ticket_id, question_text, question_order)
VALUES (16, 'Які питання розглядає філософія мови?', 5);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (80, 'Філософія мови розглядає питання природи значень, взаємовідносин між мовою і думкою, а також механізмів спілкування.', true);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (80, 'Філософія мови займається виключно структурою речень.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (80, 'Філософія мови не розглядає значення слів.', false);
INSERT INTO answer_option (question_id, option_text, is_correct)
VALUES (80, 'Філософія мови обмежується синтаксичними правилами.', false);


--Посилання
CREATE TABLE links
(
    id          int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR(255) NOT NULL,
    url         TEXT         NOT NULL,
    description TEXT,
    category    VARCHAR(50)  NOT NULL CHECK (category IN ('STUDY', 'THESIS', 'NOTES', 'ARCHIVES'))
);
